const page_1 = `<h2>Page One</h2>
                <p>This is page one. Not sure what to display here.</p>`

const page_2 = `<h2>Page Two</h2>
                <p>This is page two.</p>
                <p>I think it's fun.</p>`

const page_3 = `<h2>Page Three</h2>
                <p>This is page three with white background.</p><hr>
                <h2>Do you know?</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed enim ut sem viverra aliquet eget sit. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Elementum facilisis leo vel fringilla est ullamcorper. Nullam eget felis eget nunc lobortis. Lobortis mattis aliquam faucibus purus in. Diam donec adipiscing tristique risus nec feugiat in. Leo vel orci porta non. Ac tincidunt vitae semper quis lectus nulla. Sit amet purus gravida quis. Feugiat pretium nibh ipsum consequat nisl. Lobortis feugiat vivamus at augue eget arcu dictum varius.
                <br>
                Ante metus dictum at tempor commodo ullamcorper a lacus. Adipiscing diam donec adipiscing tristique risus nec feugiat. Turpis egestas pretium aenean pharetra. Urna duis convallis convallis tellus id interdum velit. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Dignissim suspendisse in est ante in. Et egestas quis ipsum suspendisse ultrices gravida. Vulputate enim nulla aliquet porttitor lacus luctus. Tempor nec feugiat nisl pretium fusce id velit ut tortor. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Quis eleifend quam adipiscing vitae proin sagittis. Mauris a diam maecenas sed enim ut. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Consectetur adipiscing elit duis tristique sollicitudin. Nibh tellus molestie nunc non blandit massa enim nec dui. Quis enim lobortis scelerisque fermentum dui faucibus in ornare.
                <br>
                In hendrerit gravida rutrum quisque non. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Arcu felis bibendum ut tristique et egestas. Egestas sed sed risus pretium quam vulputate. Eu nisl nunc mi ipsum faucibus vitae aliquet. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Pellentesque habitant morbi tristique senectus et. Amet nisl purus in mollis nunc sed. Ornare lectus sit amet est placerat in egestas erat imperdiet. Nibh mauris cursus mattis molestie a. Massa id neque aliquam vestibulum morbi blandit. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. In fermentum posuere urna nec tincidunt praesent semper feugiat. Massa vitae tortor condimentum lacinia quis vel eros. Amet massa vitae tortor condimentum lacinia quis vel eros. Augue ut lectus arcu bibendum at varius vel. Molestie a iaculis at erat pellentesque. Ac orci phasellus egestas tellus rutrum tellus.
                <br>
                Urna nunc id cursus metus aliquam eleifend mi in nulla. Nullam ac tortor vitae purus faucibus. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Elementum curabitur vitae nunc sed velit dignissim. Sed sed risus pretium quam vulputate dignissim suspendisse in. A diam maecenas sed enim. Volutpat sed cras ornare arcu dui. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Neque sodales ut etiam sit amet. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing.
                <br>
                Nam libero justo laoreet sit amet cursus. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. In hac habitasse platea dictumst quisque. Porta lorem mollis aliquam ut porttitor. Sed libero enim sed faucibus. Sem viverra aliquet eget sit amet. Orci a scelerisque purus semper eget duis at. Rhoncus urna neque viverra justo nec.</p>`
